on:
  schedule:
    - cron:  '0 */6 * * *'
  workflow_dispatch:
name: Main
jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: main
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Build
      run: yarn install
    - name: Main
      run: yarn start
    - name: Commit files
      run: |
        git add data.json
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "new data" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'main'