on:
  schedule:
    - cron:  '0 */6 * * *'
  workflow_dispatch:
name: New
jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: main
    - uses: actions/setup-node@v4
      with:
        node-version: '16.x'

    - name: Set env
      run: echo "PUPPETEER_DOWNLOAD_PATH=$HOME/.npm/chromium" >> $GITHUB_ENV
        
    - name: Get npm cache directory
      id: npm-cache-dir
      shell: bash
      run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
      
    - uses: actions/cache@v4
      id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
          
    - name: Build
      run: npm install
    - name: Main
      run: npm run new
    - name: Commit files
      run: |
        set +e
        git add data.json
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "new data" -a
        set -e
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'main'
